---
- name: Install the latest version of git, python3-pip, ansible-core, vim, and jq
  ansible.builtin.dnf:
    name:
      - git
      - python3-pip
      - ansible-core
      - vim
      - jq
    state: latest

- name: Clone the repo and copy lab script
  ansible.builtin.command: "{{ item }}"
  loop:
    - sudo git clone https://github.com/opentraining-labs-customizations/rh1-lab17-ocpvirt.git /opt/rh1-lab17-ocpvirt/
    - sudo cp /opt/rh1-lab17-ocpvirt/lab /usr/local/bin/
    - sudo chmod +x /usr/local/bin/lab

- name: Install the ansible-galaxy collection
  ansible.builtin.command: "ansible-galaxy collection install -r /opt/rh1-lab17-ocpvirt/requirements.yml -p /usr/share/ansible/collections/"

- name: Install the kubernetes and passlib
  ansible.builtin.command: "pip install kubernetes passlib"

#- name: Generate hashed password
#  ansible.builtin.command:
#    cmd: "openssl passwd -6 {{ common_password }}"
#  register: hashed_password
#  delegate_to: localhost
#  run_once: true

- name: Create the users on bastion
  ansible.builtin.user:
    name: "{{ ocp4_workload_authentication_htpasswd_user_base }}{{ item }}"
    state: present
    shell: /bin/bash
    password: "{{ common_password | password_hash }}"
  loop: "{{ range(1, num_users + 1) | list }}"

- name: OpenShift Access Data
  vars:
    _bastion_inventory_name: "{{ groups['bastions'][0] }}"
  agnosticd_user_info:
    user: "{{ ocp4_workload_authentication_htpasswd_user_base }}{{ item }}"
    data:
      bastion_public_hostname: "{{ _bastion_public_hostname }}"
      bastion_ssh_port: "{{ hostvars[groups['bastions'][0]].bastion_ssh_port }}"
      bastion_ssh_password: "{{ common_password }}"
      openshift_api_url: "{{ openshift_api_url }}"
  loop: "{{ range(1, num_users + 1) | list }}"

- name: Deploy Showroom
  ansible.builtin.include_role:
    name: ocp4_workload_showroom
  
- name: Authenticate on OpenShift cluster
  ansible.builtin.command:
    cmd: "oc login -u {{ openshift_cluster_admin_username }} -p {{ openshift_cluster_admin_password }} {{ openshift_api_url }}"
  register: login_result

- name: Executing lab prerequisites on cluster
  ansible.builtin.command:
    cmd: "ansible-playbook -e num_users={{ num_users }} /opt/rh1-lab17-ocpvirt/admin-configure-environment.yaml"
  register: admin_playbook_result
