---
- name: Install the latest version of git, python3-pip, ansible-core, vim, and jq
  ansible.builtin.dnf:
    name:
      - git
      - python3-pip
      - ansible-core
      - vim
      - jq
    state: latest

- name: Clone the repo and copy lab script
  ansible.builtin.command: "{{ item }}"
  loop:
    - sudo git clone https://github.com/opentraining-labs-customizations/rh1-lab17-ocpvirt.git /opt/rh1-lab17-ocpvirt/
    - sudo cp /opt/rh1-lab17-ocpvirt/lab /usr/local/bin/
    - sudo chmod +x /usr/local/bin/lab

- name: Install the ansible-galaxy collection
  ansible.builtin.command: "ansible-galaxy collection install -r /opt/rh1-lab17-ocpvirt/requirements.yml -p /usr/share/ansible/collections/"

- name: Install the kubernetes and passlib
  ansible.builtin.command: "pip install kubernetes passlib"

- name: Generate hashed password
  ansible.builtin.command:
    cmd: "openssl passwd -6 {{ common_password }}"
  register: hashed_password
  delegate_to: localhost
  run_once: true
      
- name: Create the users on bastion
  ansible.builtin.user: 
    name: "{{ ocp4_workload_authentication_htpasswd_user_base }}{{ item }}"
    state: present
    shell: /bin/bash
    password: "{{ hashed_password }}"
  loop: "{{ range(1, num_users + 1) | list }}"
